/**
 * Listing seed templates.
 *
 * One template = one canonical listing row. When `additionalChannels` is set,
 * the seeder creates extra raw_telegram_posts (one per additional channel)
 * and extra listing_sources rows pointing back to the same canonical
 * listing — this models "same property posted in multiple channels".
 *
 * Pricing rough rates (May 2026):
 *   1 USD ≈ 12,600 UZS
 *   Rent / month: 3-15M UZS or $300-1,500 in Tashkent
 *   Sale: 400M-5B UZS or $40K-500K
 *   Daily: 200K-1.5M UZS or $20-150
 *
 * Property images come from Unsplash. Some templates intentionally leave
 * mediaUrls empty so the UI's no-photo state is testable.
 *
 * Districts list comes verbatim from the master spec:
 *   Mirabad, Chilanzar, Yunusabad, Yakkasaray, Shaykhontohur, Sergeli, Almazar
 */

import type { Listing } from "../schema";

type PropertyType =
  | "apartment"
  | "house"
  | "commercial"
  | "land"
  | "room"
  | "studio";

type SeedListing = Omit<
  Listing,
  | "id"
  | "createdAt"
  | "updatedAt"
  | "categoryId"
  | "primaryRawPostId"
  | "duplicateGroupId"
  | "importedAt"
> & {
  /** Username from src/db/seed-data/channels.ts where this was posted */
  primaryChannel: string;
  /** Other channels where the same listing appeared. Adds listing_sources rows */
  additionalChannels?: string[];
  /** Unique seed key used to wire translations + duplicate groups */
  seedKey: string;
  /** If true, this listing is the canonical of a duplicate group; same group id is shared by all entries with this group tag */
  duplicateGroupTag?: string;
};

const UNSPLASH = [
  "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200",
  "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200",
  "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200",
  "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200",
  "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200",
  "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200",
  "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200",
  "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200",
];

function pics(index: number, count = 2): string[] {
  return Array.from({ length: count }).map(
    (_, i) => UNSPLASH[(index + i) % UNSPLASH.length],
  );
}

/** Helper that builds a seed listing with sensible defaults. */
function L(
  partial: Partial<SeedListing> & Pick<SeedListing, "seedKey" | "title" | "listingType" | "primaryChannel" | "city" | "publishedAt">,
): SeedListing {
  return {
    summary: null,
    originalText: null,
    detectedLanguage: "ru",
    propertyType: "apartment" as PropertyType,
    country: "Uzbekistan",
    district: null,
    neighborhood: null,
    price: null,
    currency: null,
    rooms: null,
    areaSqm: null,
    floor: null,
    totalFloors: null,
    furnished: null,
    newBuilding: null,
    renovationStatus: null,
    metroNearby: null,
    ownerOrAgent: null,
    commission: null,
    parking: null,
    balcony: null,
    elevator: null,
    petsAllowed: null,
    heatingType: null,
    buildingMaterial: null,
    contactPhone: null,
    contactTelegram: null,
    hasPhotos: false,
    mainImageUrl: null,
    mediaUrls: [],
    sourceCount: 1,
    savedCount: 0,
    extractionConfidenceJson: {},
    status: "active",
    ...partial,
  } as SeedListing;
}

const now = Date.now();
function ago(daysAgo: number): Date {
  return new Date(now - daysAgo * 24 * 60 * 60 * 1000);
}

// ---------------------------------------------------------------------------
// 30 listings
// ---------------------------------------------------------------------------

export const seedListings: SeedListing[] = [
  // ----- RENT (10) -----
  L({
    seedKey: "rent-mirabad-2br-modern",
    listingType: "rent",
    propertyType: "apartment",
    title: "Modern 2-room apartment in Mirabad",
    summary: "Renovated 2-room apartment near Magic City. Furnished, AC, washing machine.",
    originalText:
      "Сдается 2-комнатная квартира в Мирабадском районе.\nПлощадь 65м², 4/9 этаж, евроремонт, мебель и техника.\nЦена: $750/месяц.\nТел: +998901234567",
    city: "Tashkent",
    district: "Mirabad",
    neighborhood: "Magic City",
    price: "750",
    currency: "USD",
    rooms: 2,
    areaSqm: "65",
    floor: 4,
    totalFloors: 9,
    furnished: true,
    newBuilding: true,
    renovationStatus: "euro",
    metroNearby: true,
    ownerOrAgent: "agent",
    commission: "50% of one month",
    parking: false,
    balcony: true,
    elevator: true,
    petsAllowed: false,
    heatingType: "central",
    buildingMaterial: "brick",
    contactPhone: "+998901234567",
    contactTelegram: "@uzrealtor_mirabad",
    hasPhotos: true,
    mainImageUrl: pics(0)[0],
    mediaUrls: pics(0, 3),
    sourceCount: 1,
    savedCount: 18,
    publishedAt: ago(2),
    primaryChannel: "uz_realty_tashkent",
  }),
  L({
    seedKey: "rent-yunusabad-1br-cozy",
    listingType: "rent",
    propertyType: "studio",
    title: "Cozy studio in Yunusabad",
    summary: "Compact studio, 5 min from Bodomzor metro. Perfect for a single tenant.",
    originalText:
      "Сдается студия в Юнусабадском районе.\n35м², 2/5 этаж, новая мебель, рядом метро Бодомзор.\n4 500 000 сум/месяц.\n+998935551122",
    city: "Tashkent",
    district: "Yunusabad",
    price: "4500000",
    currency: "UZS",
    rooms: 1,
    areaSqm: "35",
    floor: 2,
    totalFloors: 5,
    furnished: true,
    metroNearby: true,
    ownerOrAgent: "owner",
    contactPhone: "+998935551122",
    hasPhotos: true,
    mainImageUrl: pics(1)[0],
    mediaUrls: pics(1, 2),
    sourceCount: 1,
    savedCount: 7,
    publishedAt: ago(3),
    primaryChannel: "uz_realty_tashkent",
  }),
  L({
    seedKey: "rent-chilanzar-3br-family",
    listingType: "rent",
    propertyType: "apartment",
    title: "3-bedroom family apartment in Chilanzar",
    summary: "Family-friendly flat near schools and the park. Two balconies, all utilities included.",
    originalText:
      "Сдается 3-комнатная квартира в Чиланзаре.\n90м², 6/9, без мебели, две балкона.\n8 000 000 сум/мес.\n+998973334455",
    city: "Tashkent",
    district: "Chilanzar",
    price: "8000000",
    currency: "UZS",
    rooms: 3,
    areaSqm: "90",
    floor: 6,
    totalFloors: 9,
    furnished: false,
    metroNearby: true,
    ownerOrAgent: "owner",
    parking: true,
    balcony: true,
    elevator: true,
    heatingType: "central",
    buildingMaterial: "panel",
    contactPhone: "+998973334455",
    hasPhotos: true,
    mainImageUrl: pics(2)[0],
    mediaUrls: pics(2, 4),
    sourceCount: 1,
    savedCount: 12,
    publishedAt: ago(4),
    primaryChannel: "uz_realty_tashkent",
  }),
  L({
    seedKey: "rent-yakkasaray-2br-quiet",
    listingType: "rent",
    propertyType: "apartment",
    title: "2-room flat in Yakkasaray, walk to Magic City",
    summary: "Quiet courtyard, fresh euro-renovation, dishwasher.",
    originalText:
      "Аренда 2-комнатной в Яккасарайском, тихий двор, евроремонт, посудомоечная.\n58м², 3/5.\n$550/мес. +998998887766",
    city: "Tashkent",
    district: "Yakkasaray",
    price: "550",
    currency: "USD",
    rooms: 2,
    areaSqm: "58",
    floor: 3,
    totalFloors: 5,
    furnished: true,
    renovationStatus: "euro",
    metroNearby: true,
    ownerOrAgent: "agent",
    commission: "30%",
    balcony: true,
    elevator: false,
    contactPhone: "+998998887766",
    contactTelegram: "@yakkasaray_homes",
    hasPhotos: true,
    mainImageUrl: pics(3)[0],
    mediaUrls: pics(3, 2),
    sourceCount: 1,
    savedCount: 4,
    publishedAt: ago(5),
    primaryChannel: "uz_realty_tashkent",
  }),
  L({
    seedKey: "rent-shaykhontohur-room",
    listingType: "rent",
    propertyType: "room",
    title: "Private room in 3-bedroom flat, Shaykhontohur",
    summary: "One private room, female tenants preferred. Shared kitchen and bath.",
    originalText:
      "Сдается отдельная комната в 3-комнатной, Шайхонтохурский район. Только девушка.\n14м². 1 800 000 сум/мес.\n+998935557788",
    city: "Tashkent",
    district: "Shaykhontohur",
    price: "1800000",
    currency: "UZS",
    rooms: 1,
    areaSqm: "14",
    floor: 1,
    totalFloors: 4,
    furnished: true,
    ownerOrAgent: "owner",
    contactPhone: "+998935557788",
    hasPhotos: false,
    publishedAt: ago(6),
    primaryChannel: "tashkent_rooms",
  }),
  L({
    seedKey: "rent-sergeli-2br-newbuild",
    listingType: "rent",
    propertyType: "apartment",
    title: "2-room flat in Sergeli new building",
    summary: "New residential complex, panoramic windows, kids playground.",
    originalText:
      "Сдается 2-комнатная в новостройке Сергели. Панорамные окна, детская площадка.\n55м², 7/12.\n5 000 000 сум/мес.\n+998901234890",
    city: "Tashkent",
    district: "Sergeli",
    price: "5000000",
    currency: "UZS",
    rooms: 2,
    areaSqm: "55",
    floor: 7,
    totalFloors: 12,
    furnished: true,
    newBuilding: true,
    parking: true,
    balcony: true,
    elevator: true,
    contactPhone: "+998901234890",
    hasPhotos: true,
    mainImageUrl: pics(4)[0],
    mediaUrls: pics(4, 2),
    sourceCount: 1,
    savedCount: 0,
    publishedAt: ago(7),
    primaryChannel: "uz_realty_tashkent",
  }),
  L({
    seedKey: "rent-almazar-3br-longterm",
    listingType: "rent",
    propertyType: "apartment",
    title: "Long-term 3-room rental in Almazar",
    summary: "Three rooms, separate kitchen, fully furnished, available immediately.",
    originalText:
      "Долгосрочная аренда. Олмазор. 3 комнаты, отдельная кухня, полностью с мебелью.\n78м², 4/9.\n6 800 000 сум/мес. +998935552211",
    city: "Tashkent",
    district: "Almazar",
    price: "6800000",
    currency: "UZS",
    rooms: 3,
    areaSqm: "78",
    floor: 4,
    totalFloors: 9,
    furnished: true,
    ownerOrAgent: "agent",
    commission: "50% one month",
    contactPhone: "+998935552211",
    contactTelegram: "@almazar_apartments",
    hasPhotos: true,
    mainImageUrl: pics(5)[0],
    mediaUrls: pics(5, 3),
    sourceCount: 1,
    savedCount: 9,
    publishedAt: ago(8),
    primaryChannel: "uz_realty_tashkent",
  }),
  L({
    seedKey: "rent-mirabad-premium-2br",
    listingType: "rent",
    propertyType: "apartment",
    title: "Premium 2-room with Tashkent City view",
    summary: "High floor in Tashkent City tower, smart home, designer finish, gym in building.",
    originalText:
      "Премиум 2-комнатная в Tashkent City. Дизайнерский ремонт, умный дом, спортзал.\n70м², 22/28.\n$1450/мес.\n+998901003344",
    city: "Tashkent",
    district: "Mirabad",
    neighborhood: "Tashkent City",
    price: "1450",
    currency: "USD",
    rooms: 2,
    areaSqm: "70",
    floor: 22,
    totalFloors: 28,
    furnished: true,
    newBuilding: true,
    renovationStatus: "designer",
    metroNearby: true,
    ownerOrAgent: "agent",
    parking: true,
    balcony: true,
    elevator: true,
    contactPhone: "+998901003344",
    contactTelegram: "@premium_tashkentcity",
    hasPhotos: true,
    mainImageUrl: pics(6)[0],
    mediaUrls: pics(6, 4),
    sourceCount: 1,
    savedCount: 25,
    publishedAt: ago(1),
    primaryChannel: "uz_realty_tashkent",
  }),
  L({
    seedKey: "rent-samarkand-2br",
    listingType: "rent",
    propertyType: "apartment",
    title: "Samarkand center 2-room near Registan",
    summary: "Walking distance to Registan, full renovation, AC and Wi-Fi included.",
    originalText:
      "Самарканд, центр. 2 комнаты, в шаговой доступности от Регистана.\n50м², 2/3.\n4 500 000 сум/мес.\n+998901118899",
    city: "Samarkand",
    district: null,
    price: "4500000",
    currency: "UZS",
    rooms: 2,
    areaSqm: "50",
    floor: 2,
    totalFloors: 3,
    furnished: true,
    renovationStatus: "full",
    contactPhone: "+998901118899",
    hasPhotos: true,
    mainImageUrl: pics(7)[0],
    mediaUrls: pics(7, 2),
    sourceCount: 1,
    savedCount: 3,
    publishedAt: ago(10),
    primaryChannel: "samarkand_housing",
  }),
  L({
    seedKey: "rent-chilanzar-house",
    listingType: "rent",
    propertyType: "house",
    title: "Private house with yard in Chilanzar",
    summary: "Two-story house with yard and garage. Family or small office.",
    originalText:
      "Сдается частный дом, Чиланзар. Двор, гараж, 2 этажа.\n140м², 1/2 этаж.\n12 000 000 сум/мес. +998909991122",
    city: "Tashkent",
    district: "Chilanzar",
    price: "12000000",
    currency: "UZS",
    rooms: 4,
    areaSqm: "140",
    floor: 1,
    totalFloors: 2,
    furnished: false,
    parking: true,
    balcony: false,
    elevator: false,
    petsAllowed: true,
    contactPhone: "+998909991122",
    hasPhotos: false,
    publishedAt: ago(12),
    primaryChannel: "uz_realty_tashkent",
  }),

  // ----- SALE (10) -----
  L({
    seedKey: "sale-yunusabad-3br",
    listingType: "sale",
    propertyType: "apartment",
    title: "Sale: 3-room in Yunusabad, brick building",
    summary: "Brick building, separate rooms, individual heating, ready for move-in.",
    originalText:
      "Продается 3-комнатная в Юнусабадском.\n80м², 4/9, кирпичный дом, индивидуальное отопление.\n$84 000.\n+998935550000",
    city: "Tashkent",
    district: "Yunusabad",
    price: "84000",
    currency: "USD",
    rooms: 3,
    areaSqm: "80",
    floor: 4,
    totalFloors: 9,
    furnished: false,
    metroNearby: true,
    ownerOrAgent: "owner",
    parking: false,
    balcony: true,
    elevator: true,
    heatingType: "individual",
    buildingMaterial: "brick",
    contactPhone: "+998935550000",
    hasPhotos: true,
    mainImageUrl: pics(0)[0],
    mediaUrls: pics(0, 3),
    sourceCount: 1,
    savedCount: 14,
    publishedAt: ago(3),
    primaryChannel: "uz_property_sale",
  }),
  L({
    seedKey: "sale-sergeli-studio",
    listingType: "sale",
    propertyType: "studio",
    title: "Sale: studio in new build, Sergeli",
    summary: "New complex, mortgage available, finished apartment with appliances.",
    originalText:
      "Продается студия в новостройке Сергели. Ипотека.\n38м², 6/14, отделка под ключ.\n520 000 000 сум.\n+998978889911",
    city: "Tashkent",
    district: "Sergeli",
    price: "520000000",
    currency: "UZS",
    rooms: 1,
    areaSqm: "38",
    floor: 6,
    totalFloors: 14,
    furnished: false,
    newBuilding: true,
    renovationStatus: "turnkey",
    metroNearby: false,
    contactPhone: "+998978889911",
    hasPhotos: true,
    mainImageUrl: pics(1)[0],
    mediaUrls: pics(1, 2),
    sourceCount: 1,
    savedCount: 6,
    publishedAt: ago(5),
    primaryChannel: "uz_property_sale",
  }),
  L({
    seedKey: "sale-chilanzar-2br-panel",
    listingType: "sale",
    propertyType: "apartment",
    title: "Sale: 2-room Chilanzar, panel building",
    summary: "Classic 2-room layout, good for investment or first-time buyer.",
    originalText:
      "Продается 2-комнатная Чиланзар, панельный дом.\n52м², 3/9. Хорошо для инвестиции.\n680 000 000 сум.\n+998901114455",
    city: "Tashkent",
    district: "Chilanzar",
    price: "680000000",
    currency: "UZS",
    rooms: 2,
    areaSqm: "52",
    floor: 3,
    totalFloors: 9,
    furnished: false,
    metroNearby: true,
    buildingMaterial: "panel",
    contactPhone: "+998901114455",
    hasPhotos: true,
    mainImageUrl: pics(2)[0],
    mediaUrls: pics(2, 2),
    sourceCount: 1,
    savedCount: 0,
    publishedAt: ago(7),
    primaryChannel: "uz_property_sale",
  }),
  L({
    seedKey: "sale-mirabad-penthouse",
    listingType: "sale",
    propertyType: "apartment",
    title: "Sale: penthouse with terrace, Mirabad",
    summary: "Top-floor 4-room penthouse with private terrace, panoramic city views.",
    originalText:
      "Продается пентхаус, Мирабад. 4 комнаты + терраса, панорамный вид.\n180м², 28/28.\n$298 000.\n+998998882200",
    city: "Tashkent",
    district: "Mirabad",
    price: "298000",
    currency: "USD",
    rooms: 4,
    areaSqm: "180",
    floor: 28,
    totalFloors: 28,
    furnished: true,
    newBuilding: true,
    renovationStatus: "designer",
    metroNearby: true,
    ownerOrAgent: "agent",
    parking: true,
    balcony: true,
    elevator: true,
    buildingMaterial: "monolith",
    contactPhone: "+998998882200",
    contactTelegram: "@penthouse_tashkent",
    hasPhotos: true,
    mainImageUrl: pics(3)[0],
    mediaUrls: pics(3, 5),
    sourceCount: 1,
    savedCount: 41,
    publishedAt: ago(1),
    primaryChannel: "uz_property_sale",
  }),
  L({
    seedKey: "sale-yakkasaray-2br",
    listingType: "sale",
    propertyType: "apartment",
    title: "Sale: 2-room near Magic City, investment-ready",
    summary: "Walk to Magic City, perfect for short or long-term rental investment.",
    originalText:
      "Продается 2-комнатная рядом с Magic City. Хорошо подходит для сдачи в аренду.\n64м², 7/12.\n$91 000.\n+998978881010",
    city: "Tashkent",
    district: "Yakkasaray",
    neighborhood: "Magic City",
    price: "91000",
    currency: "USD",
    rooms: 2,
    areaSqm: "64",
    floor: 7,
    totalFloors: 12,
    furnished: true,
    newBuilding: true,
    metroNearby: true,
    contactPhone: "+998978881010",
    hasPhotos: true,
    mainImageUrl: pics(4)[0],
    mediaUrls: pics(4, 2),
    sourceCount: 1,
    savedCount: 8,
    publishedAt: ago(6),
    primaryChannel: "uz_property_sale",
  }),
  L({
    seedKey: "sale-shaykhontohur-house",
    listingType: "sale",
    propertyType: "house",
    title: "Sale: 5-room cottage in Shaykhontohur",
    summary: "Private house with 6 sotok of land, garage, garden, gas and water connected.",
    originalText:
      "Продается частный дом, Шайхонтохур. 6 соток, гараж, сад.\n220м², 1/2.\n$190 000.\n+998901002233",
    city: "Tashkent",
    district: "Shaykhontohur",
    price: "190000",
    currency: "USD",
    rooms: 5,
    areaSqm: "220",
    floor: 1,
    totalFloors: 2,
    furnished: false,
    parking: true,
    contactPhone: "+998901002233",
    hasPhotos: false,
    sourceCount: 1,
    publishedAt: ago(9),
    primaryChannel: "uz_property_sale",
  }),
  L({
    seedKey: "sale-samarkand-3br",
    listingType: "sale",
    propertyType: "apartment",
    title: "Sale: Samarkand 3-room apartment",
    summary: "Renovated apartment in city center, ready to move in.",
    originalText:
      "Продается 3-комнатная Самарканд, центр. Свежий ремонт.\n75м², 3/4. 720 000 000 сум.\n+998935551100",
    city: "Samarkand",
    district: null,
    price: "720000000",
    currency: "UZS",
    rooms: 3,
    areaSqm: "75",
    floor: 3,
    totalFloors: 4,
    furnished: false,
    renovationStatus: "full",
    contactPhone: "+998935551100",
    hasPhotos: true,
    mainImageUrl: pics(5)[0],
    mediaUrls: pics(5, 2),
    sourceCount: 1,
    savedCount: 2,
    publishedAt: ago(11),
    primaryChannel: "samarkand_housing",
  }),
  L({
    seedKey: "sale-yakkasaray-commercial",
    listingType: "sale",
    propertyType: "commercial",
    title: "Sale: commercial space, Yakkasaray, ground floor",
    summary: "Commercial unit suitable for café, shop or office. High foot traffic.",
    originalText:
      "Продается коммерция, Яккасарай. 1 этаж, фасад, высокий трафик.\n95м². $145 000. +998901008877",
    city: "Tashkent",
    district: "Yakkasaray",
    price: "145000",
    currency: "USD",
    rooms: 2,
    areaSqm: "95",
    floor: 1,
    totalFloors: 5,
    furnished: false,
    newBuilding: true,
    contactPhone: "+998901008877",
    hasPhotos: true,
    mainImageUrl: pics(6)[0],
    mediaUrls: pics(6, 1),
    sourceCount: 1,
    publishedAt: ago(14),
    primaryChannel: "uz_property_sale",
  }),
  L({
    seedKey: "sale-yunusabad-1br-urgent",
    listingType: "sale",
    propertyType: "apartment",
    title: "Sale: 1-room in Yunusabad, urgent",
    summary: "Owner is relocating. Negotiable, all documents ready.",
    originalText:
      "Срочно продается 1-комнатная Юнусабад. Документы в порядке, торг.\n30м², 2/5.\n410 000 000 сум.\n+998901119988",
    city: "Tashkent",
    district: "Yunusabad",
    price: "410000000",
    currency: "UZS",
    rooms: 1,
    areaSqm: "30",
    floor: 2,
    totalFloors: 5,
    furnished: false,
    contactPhone: "+998901119988",
    hasPhotos: true,
    mainImageUrl: pics(7)[0],
    mediaUrls: pics(7, 2),
    sourceCount: 1,
    savedCount: 5,
    publishedAt: ago(2),
    primaryChannel: "uz_property_sale",
  }),
  L({
    seedKey: "sale-almazar-3br-investment",
    listingType: "sale",
    propertyType: "apartment",
    title: "Sale: 3-room in Almazar, currently rented",
    summary: "Good investment, currently rented out, mid-floor in 16-story complex.",
    originalText:
      "Продается 3-комнатная Олмазор. Сдается, инвестиция.\n78м², 9/16.\n980 000 000 сум.\n+998935557766",
    city: "Tashkent",
    district: "Almazar",
    price: "980000000",
    currency: "UZS",
    rooms: 3,
    areaSqm: "78",
    floor: 9,
    totalFloors: 16,
    furnished: true,
    newBuilding: true,
    contactPhone: "+998935557766",
    hasPhotos: true,
    mainImageUrl: pics(0)[0],
    mediaUrls: pics(0, 3),
    sourceCount: 1,
    savedCount: 11,
    publishedAt: ago(4),
    primaryChannel: "uz_property_sale",
    // Duplicate group: also posted in uz_realty_tashkent
    duplicateGroupTag: "almazar-3br-investment",
    additionalChannels: ["uz_realty_tashkent"],
  }),

  // ----- DAILY (10) -----
  L({
    seedKey: "daily-mirabad-amir-temur",
    listingType: "daily_rent",
    propertyType: "apartment",
    title: "Daily: 1-room near Amir Temur square",
    summary: "Per night rental, fast Wi-Fi, AC, ideal for business travelers.",
    originalText:
      "Посуточно. Уютная 1-комнатная у площади Амира Темура. Wi-Fi, AC.\n36м², 5/9.\n350 000 сум/сутки.\n+998935550022",
    city: "Tashkent",
    district: "Mirabad",
    neighborhood: "Amir Temur Square",
    price: "350000",
    currency: "UZS",
    rooms: 1,
    areaSqm: "36",
    floor: 5,
    totalFloors: 9,
    furnished: true,
    metroNearby: true,
    contactPhone: "+998935550022",
    hasPhotos: true,
    mainImageUrl: pics(1)[0],
    mediaUrls: pics(1, 2),
    sourceCount: 1,
    savedCount: 6,
    publishedAt: ago(1),
    primaryChannel: "uz_daily_rent",
    // Duplicate group: also posted in tashkent_rooms
    duplicateGroupTag: "daily-mirabad-amir-temur",
    additionalChannels: ["tashkent_rooms"],
  }),
  L({
    seedKey: "daily-yunusabad-2br-family",
    listingType: "daily_rent",
    propertyType: "apartment",
    title: "Daily: 2-room family flat, Yunusabad",
    summary: "Two separate rooms, kitchen with all appliances, near park and metro.",
    originalText:
      "Посуточно. 2 комнаты, Юнусабад. Кухня со всей техникой, рядом парк и метро.\n60м², 3/5.\n520 000 сум/сутки.\n+998901003344",
    city: "Tashkent",
    district: "Yunusabad",
    price: "520000",
    currency: "UZS",
    rooms: 2,
    areaSqm: "60",
    floor: 3,
    totalFloors: 5,
    furnished: true,
    metroNearby: true,
    contactPhone: "+998901003344",
    hasPhotos: true,
    mainImageUrl: pics(2)[0],
    mediaUrls: pics(2, 3),
    sourceCount: 1,
    savedCount: 1,
    publishedAt: ago(2),
    primaryChannel: "uz_daily_rent",
  }),
  L({
    seedKey: "daily-chilanzar-studio",
    listingType: "daily_rent",
    propertyType: "studio",
    title: "Daily: studio in Chilanzar, monthly discount",
    summary: "Per night or per month, discount for 7+ nights, near Mirzo Ulug'bek metro.",
    originalText:
      "Студия посуточно, Чиланзар. Скидка от 7 ночей. Рядом метро.\n30м², 4/9.\n280 000 сум/сутки.\n+998978881100",
    city: "Tashkent",
    district: "Chilanzar",
    price: "280000",
    currency: "UZS",
    rooms: 1,
    areaSqm: "30",
    floor: 4,
    totalFloors: 9,
    furnished: true,
    metroNearby: true,
    contactPhone: "+998978881100",
    hasPhotos: true,
    mainImageUrl: pics(3)[0],
    mediaUrls: pics(3, 2),
    sourceCount: 1,
    savedCount: 4,
    publishedAt: ago(3),
    primaryChannel: "uz_daily_rent",
  }),
  L({
    seedKey: "daily-yakkasaray-3br-group",
    listingType: "daily_rent",
    propertyType: "apartment",
    title: "Daily: 3-room in Yakkasaray, fits 6 guests",
    summary: "Suitable for tourist groups, three separate beds, kitchen and laundry.",
    originalText:
      "Посуточно 3 комнаты, Яккасарай. До 6 гостей, отдельные кровати, кухня, стирка.\n80м², 2/5.\n700 000 сум/сутки.\n+998935556677",
    city: "Tashkent",
    district: "Yakkasaray",
    price: "700000",
    currency: "UZS",
    rooms: 3,
    areaSqm: "80",
    floor: 2,
    totalFloors: 5,
    furnished: true,
    contactPhone: "+998935556677",
    contactTelegram: "@yakkasaray_daily",
    hasPhotos: true,
    mainImageUrl: pics(4)[0],
    mediaUrls: pics(4, 4),
    sourceCount: 1,
    savedCount: 2,
    publishedAt: ago(2),
    primaryChannel: "uz_daily_rent",
  }),
  L({
    seedKey: "daily-tashkent-city-luxury",
    listingType: "daily_rent",
    propertyType: "apartment",
    title: "Daily: luxury 2-room, Tashkent City tower",
    summary: "Premium daily rental in Tashkent City tower, concierge, gym, pool.",
    originalText:
      "Премиум посуточно, Tashkent City. Консьерж, спортзал, бассейн.\n70м², 18/28.\n$95/ночь.\n+998901112244",
    city: "Tashkent",
    district: "Mirabad",
    neighborhood: "Tashkent City",
    price: "95",
    currency: "USD",
    rooms: 2,
    areaSqm: "70",
    floor: 18,
    totalFloors: 28,
    furnished: true,
    newBuilding: true,
    renovationStatus: "designer",
    parking: true,
    balcony: true,
    elevator: true,
    contactPhone: "+998901112244",
    contactTelegram: "@tashkentcity_stays",
    hasPhotos: true,
    mainImageUrl: pics(5)[0],
    mediaUrls: pics(5, 5),
    sourceCount: 1,
    savedCount: 33,
    publishedAt: ago(1),
    primaryChannel: "uz_daily_rent",
  }),
  L({
    seedKey: "daily-sergeli-budget",
    listingType: "daily_rent",
    propertyType: "studio",
    title: "Daily: budget studio, Sergeli",
    summary: "Clean and simple, near bus stop and supermarket.",
    originalText:
      "Дешево посуточно, Сергели. Чисто, минимум удобств.\n26м², 1/4.\n180 000 сум/сутки.\n+998935551144",
    city: "Tashkent",
    district: "Sergeli",
    price: "180000",
    currency: "UZS",
    rooms: 1,
    areaSqm: "26",
    floor: 1,
    totalFloors: 4,
    furnished: true,
    contactPhone: "+998935551144",
    hasPhotos: false,
    sourceCount: 1,
    publishedAt: ago(4),
    primaryChannel: "uz_daily_rent",
  }),
  L({
    seedKey: "daily-mirabad-airport",
    listingType: "daily_rent",
    propertyType: "apartment",
    title: "Daily: 1-room near Tashkent airport",
    summary: "10 minutes from airport, ideal for transit travelers.",
    originalText:
      "Посуточно, 10 минут от аэропорта. Удобно для транзита.\n32м², 2/5.\n320 000 сум/сутки.\n+998901118877",
    city: "Tashkent",
    district: "Mirabad",
    price: "320000",
    currency: "UZS",
    rooms: 1,
    areaSqm: "32",
    floor: 2,
    totalFloors: 5,
    furnished: true,
    contactPhone: "+998901118877",
    hasPhotos: true,
    mainImageUrl: pics(6)[0],
    mediaUrls: pics(6, 2),
    sourceCount: 1,
    savedCount: 0,
    publishedAt: ago(5),
    primaryChannel: "uz_daily_rent",
  }),
  L({
    seedKey: "daily-samarkand-registan",
    listingType: "daily_rent",
    propertyType: "apartment",
    title: "Daily: Samarkand 2-room near Registan",
    summary: "Walk to Registan in 5 minutes, traditional decor, fast Wi-Fi.",
    originalText:
      "Самарканд, посуточно, 5 минут до Регистана. Традиционный декор.\n55м², 2/3.\n450 000 сум/сутки.\n+998935559988",
    city: "Samarkand",
    district: null,
    price: "450000",
    currency: "UZS",
    rooms: 2,
    areaSqm: "55",
    floor: 2,
    totalFloors: 3,
    furnished: true,
    contactPhone: "+998935559988",
    hasPhotos: true,
    mainImageUrl: pics(7)[0],
    mediaUrls: pics(7, 3),
    sourceCount: 1,
    savedCount: 16,
    publishedAt: ago(3),
    primaryChannel: "samarkand_housing",
    // Duplicate group: also posted in uz_daily_rent
    duplicateGroupTag: "daily-samarkand-registan",
    additionalChannels: ["uz_daily_rent"],
  }),
  L({
    seedKey: "daily-yakkasaray-magiccity",
    listingType: "daily_rent",
    propertyType: "apartment",
    title: "Daily: 2-room near Magic City, smart locks",
    summary: "Brand-new building, smart locks, contactless check-in.",
    originalText:
      "Посуточно, 2 комнаты возле Magic City. Умные замки, бесконтактное заселение.\n58м², 9/16.\n600 000 сум/сутки.\n+998978881212",
    city: "Tashkent",
    district: "Yakkasaray",
    neighborhood: "Magic City",
    price: "600000",
    currency: "UZS",
    rooms: 2,
    areaSqm: "58",
    floor: 9,
    totalFloors: 16,
    furnished: true,
    newBuilding: true,
    contactPhone: "+998978881212",
    contactTelegram: "@magiccity_stays",
    hasPhotos: true,
    mainImageUrl: pics(0)[0],
    mediaUrls: pics(0, 3),
    sourceCount: 1,
    savedCount: 0,
    publishedAt: ago(2),
    primaryChannel: "uz_daily_rent",
  }),
  L({
    seedKey: "daily-shaykhontohur-room",
    listingType: "daily_rent",
    propertyType: "room",
    title: "Daily: cozy room in Shaykhontohur, host on site",
    summary: "Private room with shared kitchen, host on site, breakfast included.",
    originalText:
      "Посуточно, отдельная комната, Шайхонтохур. Завтрак включен, хозяин на месте.\n18м², 1/2.\n220 000 сум/сутки.\n+998935557799",
    city: "Tashkent",
    district: "Shaykhontohur",
    price: "220000",
    currency: "UZS",
    rooms: 1,
    areaSqm: "18",
    floor: 1,
    totalFloors: 2,
    furnished: true,
    contactPhone: "+998935557799",
    hasPhotos: false,
    sourceCount: 1,
    savedCount: 0,
    publishedAt: ago(6),
    primaryChannel: "tashkent_rooms",
  }),
];
