/**
 * Mock listing templates. Combined with locations/channels in seed.ts to
 * produce ~50 deterministic listings spanning rent / sale / daily.
 *
 * Prices are in UZS (Uzbek Som) — current rough rate is ~12,600 UZS = 1 USD.
 * priceUsd is computed in seed.ts using this constant.
 */

export const UZS_PER_USD = 12600;

export type SeedListingType = "rent" | "sale" | "daily";

export type SeedListingTemplate = {
  type: SeedListingType;
  title: string;
  description: string;
  priceUzs: number;
  rooms: number | null;
  areaSqm: number | null;
  floor: number | null;
  totalFloors: number | null;
  furnished: boolean | null;
  /** Optional district slug suffix; matched to tashkentDistricts in seed.ts */
  districtSlug?: string;
  /** Optional city slug override; defaults to "tashkent" */
  citySlug?: string;
  /** Phone numbers attached to the listing */
  contactPhones: string[];
  /** Channel username (must exist in seedChannels) */
  channelUsername: string;
};

const photos = [
  "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900",
  "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=900",
  "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900",
  "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=900",
  "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=900",
];

export function pickPhotos(index: number): string[] {
  return [photos[index % photos.length], photos[(index + 2) % photos.length]];
}

export const seedListingTemplates: SeedListingTemplate[] = [
  // ---- RENT ----
  {
    type: "rent",
    title: "Bright 2-room apartment in Mirzo Ulug'bek",
    description:
      "Spacious 2-room apartment, recently renovated, near Buyuk Ipak Yo'li metro. Includes kitchen appliances and air conditioning.",
    priceUzs: 6_500_000,
    rooms: 2,
    areaSqm: 65,
    floor: 4,
    totalFloors: 9,
    furnished: true,
    districtSlug: "tashkent-mirzo-ulugbek",
    contactPhones: ["+998901234567"],
    channelUsername: "uz_realty_tashkent",
  },
  {
    type: "rent",
    title: "Cozy 1-room studio in Yunusabad",
    description:
      "Compact studio with new furniture, perfect for a single tenant. 5 minutes from Bodomzor metro.",
    priceUzs: 4_200_000,
    rooms: 1,
    areaSqm: 35,
    floor: 2,
    totalFloors: 5,
    furnished: true,
    districtSlug: "tashkent-yunusabad",
    contactPhones: ["+998935551122"],
    channelUsername: "uz_realty_tashkent",
  },
  {
    type: "rent",
    title: "3-bedroom family flat in Chilanzar",
    description:
      "Family-friendly, near schools and the park. Two balconies, gas, all utilities included.",
    priceUzs: 8_000_000,
    rooms: 3,
    areaSqm: 90,
    floor: 6,
    totalFloors: 9,
    furnished: false,
    districtSlug: "tashkent-chilanzar",
    contactPhones: ["+998973334455"],
    channelUsername: "uz_realty_tashkent",
  },
  {
    type: "rent",
    title: "Modern studio near Mirobod metro",
    description:
      "Newly built complex, gym in the building, 24/7 security. Long-term rent only.",
    priceUzs: 5_500_000,
    rooms: 1,
    areaSqm: 42,
    floor: 8,
    totalFloors: 16,
    furnished: true,
    districtSlug: "tashkent-mirobod",
    contactPhones: ["+998901112233"],
    channelUsername: "tashkent_rooms",
  },
  {
    type: "rent",
    title: "Yakkasaray 2-room near Oybek",
    description:
      "Quiet courtyard, central location, fresh euro-renovation, washing machine and dishwasher.",
    priceUzs: 7_000_000,
    rooms: 2,
    areaSqm: 58,
    floor: 3,
    totalFloors: 5,
    furnished: true,
    districtSlug: "tashkent-yakkasaray",
    contactPhones: ["+998998887766"],
    channelUsername: "uz_realty_tashkent",
  },
  {
    type: "rent",
    title: "Room in shared apartment, Shaykhantakhur",
    description:
      "Single private room in a 3-room flat with two other tenants. Female tenants preferred.",
    priceUzs: 1_800_000,
    rooms: 1,
    areaSqm: 14,
    floor: 1,
    totalFloors: 4,
    furnished: true,
    districtSlug: "tashkent-shaykhantakhur",
    contactPhones: ["+998935557788"],
    channelUsername: "tashkent_rooms",
  },
  {
    type: "rent",
    title: "4-room townhouse, Yashnobod",
    description:
      "Two-story townhouse with private yard and parking. Suitable for large family or office.",
    priceUzs: 12_000_000,
    rooms: 4,
    areaSqm: 140,
    floor: 1,
    totalFloors: 2,
    furnished: false,
    districtSlug: "tashkent-yashnobod",
    contactPhones: ["+998909991122"],
    channelUsername: "uz_realty_tashkent",
  },
  {
    type: "rent",
    title: "Affordable 1-room in Uchtepa",
    description:
      "Budget option, basic furniture, gas water heater. Walk to bus stop and market.",
    priceUzs: 2_500_000,
    rooms: 1,
    areaSqm: 32,
    floor: 5,
    totalFloors: 5,
    furnished: true,
    districtSlug: "tashkent-uchtepa",
    contactPhones: ["+998978889944"],
    channelUsername: "uz_realty_tashkent",
  },
  {
    type: "rent",
    title: "2-room apartment in Sergeli, new building",
    description:
      "New residential complex, panoramic windows, kids playground in courtyard.",
    priceUzs: 5_000_000,
    rooms: 2,
    areaSqm: 55,
    floor: 7,
    totalFloors: 12,
    furnished: true,
    districtSlug: "tashkent-sergeli",
    contactPhones: ["+998901234890"],
    channelUsername: "uz_realty_tashkent",
  },
  {
    type: "rent",
    title: "Long-term rent, Olmazor 3 rooms",
    description:
      "Three rooms, separate kitchen, fully furnished, available immediately.",
    priceUzs: 6_800_000,
    rooms: 3,
    areaSqm: 78,
    floor: 4,
    totalFloors: 9,
    furnished: true,
    districtSlug: "tashkent-olmazor",
    contactPhones: ["+998935552211"],
    channelUsername: "uz_realty_tashkent",
  },
  {
    type: "rent",
    title: "Samarkand center 2-room",
    description:
      "Walking distance to Registan, full renovation, AC and Wi-Fi included.",
    priceUzs: 4_500_000,
    rooms: 2,
    areaSqm: 50,
    floor: 2,
    totalFloors: 3,
    furnished: true,
    citySlug: "samarkand",
    contactPhones: ["+998901118899"],
    channelUsername: "samarkand_housing",
  },
  {
    type: "rent",
    title: "Bukhara 1-room flat near old city",
    description:
      "Traditional layout, courtyard view, suitable for digital nomads.",
    priceUzs: 3_500_000,
    rooms: 1,
    areaSqm: 38,
    floor: 1,
    totalFloors: 2,
    furnished: true,
    citySlug: "bukhara",
    contactPhones: ["+998935553344"],
    channelUsername: "uz_realty_tashkent",
  },
  {
    type: "rent",
    title: "Studio for student, Mirzo Ulug'bek",
    description:
      "Right next to TUIT campus, basic furniture, fast internet.",
    priceUzs: 3_000_000,
    rooms: 1,
    areaSqm: 28,
    floor: 3,
    totalFloors: 4,
    furnished: true,
    districtSlug: "tashkent-mirzo-ulugbek",
    contactPhones: ["+998977776655"],
    channelUsername: "tashkent_rooms",
  },
  {
    type: "rent",
    title: "Premium 3-room Mirobod, Tashkent City view",
    description:
      "High floor with view of Tashkent City complex, designer finish, smart home.",
    priceUzs: 18_000_000,
    rooms: 3,
    areaSqm: 110,
    floor: 22,
    totalFloors: 28,
    furnished: true,
    districtSlug: "tashkent-mirobod",
    contactPhones: ["+998901003344"],
    channelUsername: "uz_realty_tashkent",
  },
  {
    type: "rent",
    title: "2-room, Yakkasaray, near Magic City",
    description:
      "Beautifully renovated, walk to Magic City and Yakkasaray park.",
    priceUzs: 9_500_000,
    rooms: 2,
    areaSqm: 70,
    floor: 5,
    totalFloors: 9,
    furnished: true,
    districtSlug: "tashkent-yakkasaray",
    contactPhones: ["+998998881122"],
    channelUsername: "uz_realty_tashkent",
  },

  // ---- SALE ----
  {
    type: "sale",
    title: "Sale: 3-room in Yunusabad, 4/9",
    description:
      "Brick building, separate rooms, individual heating, ready for move-in.",
    priceUzs: 1_050_000_000,
    rooms: 3,
    areaSqm: 80,
    floor: 4,
    totalFloors: 9,
    furnished: false,
    districtSlug: "tashkent-yunusabad",
    contactPhones: ["+998935550000"],
    channelUsername: "uz_property_sale",
  },
  {
    type: "sale",
    title: "Sale: studio in new build, Sergeli",
    description:
      "New complex, mortgage available, finished apartment with appliances.",
    priceUzs: 520_000_000,
    rooms: 1,
    areaSqm: 38,
    floor: 6,
    totalFloors: 14,
    furnished: false,
    districtSlug: "tashkent-sergeli",
    contactPhones: ["+998978889911"],
    channelUsername: "uz_property_sale",
  },
  {
    type: "sale",
    title: "Sale: 2-room Chilanzar, panel",
    description:
      "Classic 2-room layout, good for investment or first-time buyer.",
    priceUzs: 680_000_000,
    rooms: 2,
    areaSqm: 52,
    floor: 3,
    totalFloors: 9,
    furnished: false,
    districtSlug: "tashkent-chilanzar",
    contactPhones: ["+998901114455"],
    channelUsername: "uz_property_sale",
  },
  {
    type: "sale",
    title: "Sale: 4-room family flat, Mirzo Ulug'bek",
    description:
      "Spacious 4-room, two balconies, requires light cosmetic renovation.",
    priceUzs: 1_400_000_000,
    rooms: 4,
    areaSqm: 105,
    floor: 5,
    totalFloors: 9,
    furnished: false,
    districtSlug: "tashkent-mirzo-ulugbek",
    contactPhones: ["+998935559900"],
    channelUsername: "uz_property_sale",
  },
  {
    type: "sale",
    title: "Sale: penthouse, Mirobod",
    description:
      "Top-floor 4-room penthouse with terrace, panoramic city views.",
    priceUzs: 3_800_000_000,
    rooms: 4,
    areaSqm: 180,
    floor: 28,
    totalFloors: 28,
    furnished: true,
    districtSlug: "tashkent-mirobod",
    contactPhones: ["+998998882200"],
    channelUsername: "uz_property_sale",
  },
  {
    type: "sale",
    title: "Sale: 1-room in Uchtepa, urgent",
    description:
      "Owner is relocating. Negotiable, all documents ready.",
    priceUzs: 410_000_000,
    rooms: 1,
    areaSqm: 30,
    floor: 2,
    totalFloors: 5,
    furnished: false,
    districtSlug: "tashkent-uchtepa",
    contactPhones: ["+998901119988"],
    channelUsername: "uz_property_sale",
  },
  {
    type: "sale",
    title: "Sale: 2-room near Magic City",
    description:
      "Walk to Magic City, perfect for short or long-term rental investment.",
    priceUzs: 1_150_000_000,
    rooms: 2,
    areaSqm: 64,
    floor: 7,
    totalFloors: 12,
    furnished: true,
    districtSlug: "tashkent-yakkasaray",
    contactPhones: ["+998978881010"],
    channelUsername: "uz_property_sale",
  },
  {
    type: "sale",
    title: "Sale: 3-room in Yashnobod",
    description:
      "Good investment, currently rented out, mid-floor in 16-story complex.",
    priceUzs: 980_000_000,
    rooms: 3,
    areaSqm: 78,
    floor: 9,
    totalFloors: 16,
    furnished: false,
    districtSlug: "tashkent-yashnobod",
    contactPhones: ["+998935557766"],
    channelUsername: "uz_property_sale",
  },
  {
    type: "sale",
    title: "Sale: 5-room cottage in Bektemir",
    description:
      "Private house with land, 6 sotok, garage, garden, gas and water connected.",
    priceUzs: 2_400_000_000,
    rooms: 5,
    areaSqm: 220,
    floor: 1,
    totalFloors: 2,
    furnished: false,
    districtSlug: "tashkent-bektemir",
    contactPhones: ["+998901002233"],
    channelUsername: "uz_property_sale",
  },
  {
    type: "sale",
    title: "Sale: Samarkand 3-room apartment",
    description:
      "Renovated apartment in city center, ready to move in.",
    priceUzs: 720_000_000,
    rooms: 3,
    areaSqm: 75,
    floor: 3,
    totalFloors: 4,
    furnished: false,
    citySlug: "samarkand",
    contactPhones: ["+998935551100"],
    channelUsername: "samarkand_housing",
  },
  {
    type: "sale",
    title: "Sale: Andijan 2-room",
    description:
      "Quiet neighborhood, brick building, near schools and clinics.",
    priceUzs: 410_000_000,
    rooms: 2,
    areaSqm: 54,
    floor: 4,
    totalFloors: 5,
    furnished: false,
    citySlug: "andijan",
    contactPhones: ["+998901008877"],
    channelUsername: "uz_property_sale",
  },
  {
    type: "sale",
    title: "Sale: 2-room in Namangan center",
    description:
      "Center of Namangan, walking distance to bazaar and city park.",
    priceUzs: 450_000_000,
    rooms: 2,
    areaSqm: 55,
    floor: 2,
    totalFloors: 5,
    furnished: false,
    citySlug: "namangan",
    contactPhones: ["+998978886655"],
    channelUsername: "uz_property_sale",
  },
  {
    type: "sale",
    title: "Sale: 1-room in Fergana",
    description:
      "Compact 1-room near university campus, well maintained.",
    priceUzs: 320_000_000,
    rooms: 1,
    areaSqm: 36,
    floor: 1,
    totalFloors: 5,
    furnished: false,
    citySlug: "fergana",
    contactPhones: ["+998935554433"],
    channelUsername: "uz_property_sale",
  },
  {
    type: "sale",
    title: "Sale: 2-room in Bukhara, near tourist zone",
    description:
      "Excellent for rental income, in walking distance from Lyabi-Hauz.",
    priceUzs: 620_000_000,
    rooms: 2,
    areaSqm: 58,
    floor: 2,
    totalFloors: 3,
    furnished: true,
    citySlug: "bukhara",
    contactPhones: ["+998901001122"],
    channelUsername: "uz_property_sale",
  },

  // ---- DAILY ----
  {
    type: "daily",
    title: "Daily: cozy 1-room near Amir Temur square",
    description:
      "Per night rental, fast Wi-Fi, AC, ideal for business travelers.",
    priceUzs: 350_000,
    rooms: 1,
    areaSqm: 36,
    floor: 5,
    totalFloors: 9,
    furnished: true,
    districtSlug: "tashkent-mirobod",
    contactPhones: ["+998935550022"],
    channelUsername: "uz_daily_rent",
  },
  {
    type: "daily",
    title: "Daily: 2-room family flat, Yunusabad",
    description:
      "Two separate rooms, kitchen with all appliances, near park and metro.",
    priceUzs: 520_000,
    rooms: 2,
    areaSqm: 60,
    floor: 3,
    totalFloors: 5,
    furnished: true,
    districtSlug: "tashkent-yunusabad",
    contactPhones: ["+998901003344"],
    channelUsername: "uz_daily_rent",
  },
  {
    type: "daily",
    title: "Daily: studio in Chilanzar, monthly discount",
    description:
      "Per night or per month, discount for 7+ nights, near metro Mirzo Ulug'bek.",
    priceUzs: 280_000,
    rooms: 1,
    areaSqm: 30,
    floor: 4,
    totalFloors: 9,
    furnished: true,
    districtSlug: "tashkent-chilanzar",
    contactPhones: ["+998978881100"],
    channelUsername: "uz_daily_rent",
  },
  {
    type: "daily",
    title: "Daily: 3-room in Yakkasaray",
    description:
      "Suitable for tourist groups, three separate beds, kitchen and laundry.",
    priceUzs: 700_000,
    rooms: 3,
    areaSqm: 80,
    floor: 2,
    totalFloors: 5,
    furnished: true,
    districtSlug: "tashkent-yakkasaray",
    contactPhones: ["+998935556677"],
    channelUsername: "uz_daily_rent",
  },
  {
    type: "daily",
    title: "Daily: luxury 2-room, Tashkent City",
    description:
      "Premium daily rental in Tashkent City tower, concierge, gym, pool.",
    priceUzs: 1_200_000,
    rooms: 2,
    areaSqm: 70,
    floor: 18,
    totalFloors: 28,
    furnished: true,
    districtSlug: "tashkent-mirobod",
    contactPhones: ["+998901112244"],
    channelUsername: "uz_daily_rent",
  },
  {
    type: "daily",
    title: "Daily: budget studio, Sergeli",
    description:
      "Clean and simple, near bus stop and supermarket.",
    priceUzs: 180_000,
    rooms: 1,
    areaSqm: 26,
    floor: 1,
    totalFloors: 4,
    furnished: true,
    districtSlug: "tashkent-sergeli",
    contactPhones: ["+998935551144"],
    channelUsername: "uz_daily_rent",
  },
  {
    type: "daily",
    title: "Daily: family 4-room, Mirzo Ulug'bek",
    description:
      "Large flat for groups up to 6, two bathrooms, parking available.",
    priceUzs: 900_000,
    rooms: 4,
    areaSqm: 120,
    floor: 6,
    totalFloors: 9,
    furnished: true,
    districtSlug: "tashkent-mirzo-ulugbek",
    contactPhones: ["+998978889922"],
    channelUsername: "uz_daily_rent",
  },
  {
    type: "daily",
    title: "Daily: 1-room near Tashkent airport",
    description:
      "10 minutes from airport, ideal for transit travelers.",
    priceUzs: 320_000,
    rooms: 1,
    areaSqm: 32,
    floor: 2,
    totalFloors: 5,
    furnished: true,
    districtSlug: "tashkent-bektemir",
    contactPhones: ["+998901118877"],
    channelUsername: "uz_daily_rent",
  },
  {
    type: "daily",
    title: "Daily: Samarkand 2-room near Registan",
    description:
      "Walk to Registan in 5 minutes, traditional decor, fast Wi-Fi.",
    priceUzs: 450_000,
    rooms: 2,
    areaSqm: 55,
    floor: 2,
    totalFloors: 3,
    furnished: true,
    citySlug: "samarkand",
    contactPhones: ["+998935559988"],
    channelUsername: "samarkand_housing",
  },
  {
    type: "daily",
    title: "Daily: Bukhara 1-room courtyard apartment",
    description:
      "Traditional Bukhara house apartment, tea on the porch included.",
    priceUzs: 380_000,
    rooms: 1,
    areaSqm: 40,
    floor: 1,
    totalFloors: 2,
    furnished: true,
    citySlug: "bukhara",
    contactPhones: ["+998901002211"],
    channelUsername: "uz_daily_rent",
  },
  {
    type: "daily",
    title: "Daily: 2-room near Magic City",
    description:
      "Brand-new building, smart locks, contactless check-in.",
    priceUzs: 600_000,
    rooms: 2,
    areaSqm: 58,
    floor: 9,
    totalFloors: 16,
    furnished: true,
    districtSlug: "tashkent-yakkasaray",
    contactPhones: ["+998978881212"],
    channelUsername: "uz_daily_rent",
  },
  {
    type: "daily",
    title: "Daily: cozy room in Shaykhantakhur",
    description:
      "Private room with shared kitchen, host on site, breakfast included.",
    priceUzs: 220_000,
    rooms: 1,
    areaSqm: 18,
    floor: 1,
    totalFloors: 2,
    furnished: true,
    districtSlug: "tashkent-shaykhantakhur",
    contactPhones: ["+998935557799"],
    channelUsername: "uz_daily_rent",
  },
  {
    type: "daily",
    title: "Daily: 1-room near Tashkent State University",
    description:
      "Walk to university campus, suitable for visiting researchers and students.",
    priceUzs: 260_000,
    rooms: 1,
    areaSqm: 30,
    floor: 4,
    totalFloors: 5,
    furnished: true,
    districtSlug: "tashkent-uchtepa",
    contactPhones: ["+998901119900"],
    channelUsername: "uz_daily_rent",
  },
  {
    type: "daily",
    title: "Daily: Yashnobod 2-room with parking",
    description:
      "Underground parking included, building has 24/7 security.",
    priceUzs: 540_000,
    rooms: 2,
    areaSqm: 62,
    floor: 5,
    totalFloors: 12,
    furnished: true,
    districtSlug: "tashkent-yashnobod",
    contactPhones: ["+998978886633"],
    channelUsername: "uz_daily_rent",
  },
  {
    type: "daily",
    title: "Daily: budget 1-room in Olmazor",
    description:
      "Affordable, simple, includes towels and bedding.",
    priceUzs: 200_000,
    rooms: 1,
    areaSqm: 28,
    floor: 2,
    totalFloors: 5,
    furnished: true,
    districtSlug: "tashkent-olmazor",
    contactPhones: ["+998935553311"],
    channelUsername: "uz_daily_rent",
  },
];
